### ISSUE TITLE
Would I be able to use rspec method 'match_json_expression' inside a cucumber step definitions?

### ISSUE THREAD

**Issue by sbsabapathi** [chancancode/json_expressions#31]
Hi there, 

I found this very useful in my project. however this only seems to work with rspec tests. Is there any way I could make use of it in cucumber step definitions?

**Comment by MiroslavCsonka** [comment]
Hi, https://github.com/chancancode/json_expressions/issues/20 could help you. I'm using [json_expressions](https://github.com/chancancode/json_expressions) with cucumber and I'm more than happy.

**Comment by sbsabapathi** [comment]
Thanks for your help. I was able to get it to work on cucumber too using your suggestion. Just forgot to close the issue
