### ISSUE TITLE
Add support for unified Integer class

### ISSUE THREAD

**Issue by Dschee** [chancancode/json_expressions#38]
Ruby 2.4 first deprecates the Fixnum and Bignum classes in favor of the new Integer class, which unifies both into one. When using this gem in Ruby 2.4.0 I get the following warnings:

```shell
.rvm/gems/ruby-2.4.0/gems/json_expressions-0.8.3/lib/json_expressions/matcher.rb:175: warning: constant ::Fixnum is deprecated
```

Adding support for the Integer seems to be missing.

**Comment by iamliamnorton** [comment]
PR submitted https://github.com/chancancode/json_expressions/pull/39 to address this issue.

**Comment by MiroslavCsonka** [comment]
Closed by https://github.com/chancancode/json_expressions/pull/39
